from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name="Category", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=80, unique=True, verbose_name="名称")), ("slug", models.SlugField(allow_unicode=True, max_length=90, unique=True, verbose_name="网址标识"))], options={"verbose_name": "分类", "verbose_name_plural": "分类"}),
        migrations.CreateModel(name="SiteSetting", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(default="片刻", max_length=80, verbose_name="站点名称")), ("tagline", models.CharField(default="记录日常所想", max_length=160, verbose_name="一句话介绍")), ("author", models.CharField(blank=True, max_length=80, verbose_name="作者")), ("about", models.TextField(blank=True, verbose_name="关于（Markdown）")), ("footer", models.CharField(blank=True, max_length=160, verbose_name="页脚文字"))], options={"verbose_name": "站点设置", "verbose_name_plural": "站点设置"}),
        migrations.CreateModel(name="Tag", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=80, unique=True, verbose_name="名称")), ("slug", models.SlugField(allow_unicode=True, max_length=90, unique=True, verbose_name="网址标识"))], options={"verbose_name": "标签", "verbose_name_plural": "标签"}),
        migrations.CreateModel(name="Post", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=180, verbose_name="标题")), ("slug", models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name="网址标识")), ("excerpt", models.TextField(blank=True, max_length=300, verbose_name="摘要")), ("body", models.TextField(verbose_name="正文（Markdown）")), ("cover", models.ImageField(blank=True, upload_to="covers/%Y/%m/", verbose_name="封面")), ("status", models.CharField(choices=[("draft", "草稿"), ("published", "已发布")], default="draft", max_length=12, verbose_name="状态")), ("published_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="发布时间")), ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")), ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")), ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="posts", to="blog.category", verbose_name="分类")), ("tags", models.ManyToManyField(blank=True, related_name="posts", to="blog.tag", verbose_name="标签"))], options={"verbose_name": "文章", "verbose_name_plural": "文章", "ordering": ["-published_at"]}),
    ]

